services:
  database:
    profiles:
      - dev
      - local
    image: postgres:alpine
    container_name: db
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: blog-api
      PGTZ: America/Recife
    ports:
      - "5432:5432"
    networks:
      - blog-network

  storage:
    profiles:
      - dev
      - local
    container_name: minio
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - storage:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: adminpass
    command: server /data --console-address ":9001"
    networks:
      - blog-network

  create-required-buckets:
    profiles:
      - dev
      - local
    image: minio/mc
    depends_on:
      - storage
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      mc alias set myminio http://minio:9000 admin adminpass &&
      mc mb myminio/users &&
      mc mb myminio/posts &&
      mc mb myminio/temp &&
      mc anonymous set public myminio/temp &&
      mc policy set download myminio/temp
      "
    networks:
      - blog-network

networks:
  blog-network:

volumes:
  database:
  storage:
    driver: local
